name: Deploy Nuxt App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Cleanup existing repository
        run: |
          cd /home/nathan/apps  # Remplacez par la racine où vous stockez les projets
          rm -rf portfolio

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: portfolio

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd /home/nathan/apps/portfolio
          npm install

      - name: Build the application
        run: |
      
          npm run build

      - name: Deploy to server
        run: |
       
          pm2 stop portfolio || true
          pm2 delete portfolio || true
          pm2 start npm --name "portfolio" -- run start
