name: Deploy Nuxt App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
         
      - name: Build and run Docker container
        run: |
        
          docker build -t portfolio .
          docker stop portfolio || true
          docker rm portfolio || true
          docker run -d --name portfolio -p 3002:3002 portfolio

      - name: Manage with PM2
        run: |
          pm2 stop portfolio || true
          pm2 delete portfolio || true
          pm2 start "docker start portfolio" --name portfolio --restart-delay=5000
